ALTER TABLE user_goals
    ADD COLUMN IF NOT EXISTS image_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS coins_reward INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS coins_reward_with_image INTEGER NOT NULL DEFAULT 25;
