ALTER TABLE user_detail
    ADD COLUMN IF NOT EXISTS interface_volume DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    ADD COLUMN IF NOT EXISTS ambient_volume DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    ADD COLUMN IF NOT EXISTS minigame_volume DOUBLE PRECISION NOT NULL DEFAULT 1.0;
