UPDATE activity
SET type = CASE type
    WHEN 'RESPIRACION' THEN 'BREATHING'
    WHEN 'DIARIO' THEN 'DIARY'
    WHEN 'NUBE' THEN 'LANTERN'
    WHEN 'BURBUJA' THEN 'BUBBLE'
    WHEN 'RETO' THEN 'CHALLENGE'
    WHEN 'ARENA_ZEN' THEN 'ZEN_GARDEN'
    ELSE type
END
WHERE type IN ('RESPIRACION', 'DIARIO', 'NUBE', 'BURBUJA', 'RETO', 'ARENA_ZEN');

UPDATE activity_sessions
SET activity_type = CASE activity_type
    WHEN 'RESPIRACION' THEN 'BREATHING'
    WHEN 'DIARIO' THEN 'DIARY'
    WHEN 'NUBE' THEN 'LANTERN'
    WHEN 'BURBUJA' THEN 'BUBBLE'
    WHEN 'RETO' THEN 'CHALLENGE'
    WHEN 'ARENA_ZEN' THEN 'ZEN_GARDEN'
    ELSE activity_type
END
WHERE activity_type IN ('RESPIRACION', 'DIARIO', 'NUBE', 'BURBUJA', 'RETO', 'ARENA_ZEN');

UPDATE chat_message
SET suggested_action_type = CASE suggested_action_type
    WHEN 'RESPIRACION' THEN 'BREATHING'
    WHEN 'DIARIO' THEN 'DIARY'
    WHEN 'NUBE' THEN 'LANTERN'
    WHEN 'BURBUJA' THEN 'BUBBLE'
    WHEN 'RETO' THEN 'CHALLENGE'
    WHEN 'ARENA_ZEN' THEN 'ZEN_GARDEN'
    ELSE suggested_action_type
END
WHERE suggested_action_type IN ('RESPIRACION', 'DIARIO', 'NUBE', 'BURBUJA', 'RETO', 'ARENA_ZEN');
