ALTER TABLE pendiente_task RENAME TO pending_task;
ALTER TABLE pendiente_subtask RENAME TO pending_subtask;
ALTER TABLE pendiente_daily_recommendation RENAME TO pending_daily_recommendation;
ALTER TABLE pendiente_daily_recommendation_task RENAME TO pending_daily_recommendation_task;

ALTER INDEX idx_pendiente_task_user_status RENAME TO idx_pending_task_user_status;
ALTER INDEX idx_pendiente_subtask_task_id RENAME TO idx_pending_subtask_task_id;
ALTER INDEX idx_pendiente_reco_task_reco_id RENAME TO idx_pending_reco_task_reco_id;
ALTER INDEX idx_pendiente_reco_task_task_id RENAME TO idx_pending_reco_task_task_id;

ALTER TABLE pending_daily_recommendation
    RENAME CONSTRAINT uq_pendiente_daily_recommendation_user_date TO uq_pending_daily_recommendation_user_date;
ALTER TABLE pending_daily_recommendation_task
    RENAME CONSTRAINT uq_pendiente_reco_task TO uq_pending_reco_task;
