INSERT INTO store_item (name, description, category, asset_key, price_coins) VALUES
    ('Remera violeta', 'Una remera violeta bien copada para tu personaje', 'SHIRT', 'remera-violeta', 14200),
    ('Zapatillas blancas', 'Zapatillas blancas para caminar comodo', 'SHOES', 'zapatillas-blancas', 12500),
    ('Visera azul', 'Una visera azul para protegerse del sol', 'HAT', 'vicera-azul', 50000),
    ('Remera rosa', 'Una remera rosa bien copada para tu personaje', 'SHIRT', 'remera-rosa', 14200),
    ('Remera azul', 'Una remera azul bien copada para tu personaje', 'SHIRT', 'remera-azul', 14200),
    ('Visera rosa', 'Una visera rosa para protegerse del sol', 'HAT', 'vicera-rosa', 50000),
    ('Visera cafe', 'Una visera cafe para protegerse del sol', 'HAT', 'vicera-cafe', 50000),
    ('Jardinero rosa', 'Un jardinero color rosa', 'SHIRT', 'jardinero-rosa', 20000),
    ('Jardinero gris', 'Un jardinero color gris con bolsillo blanco', 'SHIRT', 'jardinero-gris', 20000),
    ('Remera mostaza', 'Una remera color mostaza muy aventurera', 'SHIRT', 'remera-mostaza', 14500),
    ('Remera turquesa', 'Remera turquesa fresca y moderna', 'SHIRT', 'remera-turquesa', 15000),
    ('Remera carmesí', 'Remera carmesí con mucha energía', 'SHIRT', 'remera-carmesi', 15000),
    ('Remera lavanda', 'Una remera lavanda que transmite paz', 'SHIRT', 'remera-lavanda', 14500),
    ('Remera carbón', 'La clásica remera oscura que combina con todo', 'SHIRT', 'remera-carbon', 16000),
    ('Jardinero mostaza', 'Jardinero cálido para aventuras al aire libre', 'SHIRT', 'jardinero-mostaza', 20000),
    ('Jardinero carbón', 'Jardinero gris oscuro elegante y minimalista', 'SHIRT', 'jardinero-carbon', 22000),
    ('Visera turquesa', 'Para el sol, con estilo fresco', 'HAT', 'vicera-turquesa', 50000),
    ('Visera carmesí', 'Destaca a lo lejos con esta visera', 'HAT', 'vicera-carmesi', 52000),
    ('Visera carbón', 'Discreta pero moderna', 'HAT', 'vicera-carbon', 55000),
    ('Zapatillas rojas', 'Zapatillas rojas clásicas y llamativas', 'SHOES', 'zapatillas-rojas', 15000),
    ('Zapatillas negras', 'Zapatillas oscuras para un look urbano', 'SHOES', 'zapatillas-negras', 16500),
    ('Zapatillas verdes', 'Combina perfectamente con tu cabello', 'SHOES', 'zapatillas-verdes', 14500);
