spring.config.import=classpath:application-huly-secrets.properties

#SERVER
server.port=${PORT:8080}
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${user.home}/.huly/ssl/localhost.p12
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD:secret123}
server.ssl.key-alias=localhost
#cambiar a true para usar https
server.ssl.enabled=false


#CORS
frontend.url=${FRONTEND_URL}

#DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#SWAGGER
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#SPRING AI - Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.chat.options.temperature=0.7



