
#SERVER
server.port=8080

#CORS
frontend.url=http://localhost:5173

#DATABASE - H2 en memoria para dev (comentar cuando haya PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d7o12pugvqtc73b5rrug-a.oregon-postgres.render.com:5432/huly
spring.datasource.username=huly_user
spring.datasource.password=oNBIMLnmZ0stFSe8SsgRUg83fB7UXGBi
#spring.datasource.url=jdbc:h2:mem:hulydev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#JPA - auto-crea el schema desde las entidades en dev
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#FLYWAY - deshabilitado en dev (usamos ddl-auto en su lugar)
spring.flyway.enabled=true

#SPRING AI JDBC - inicializar schema automaticamente
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

#SWAGGER
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.chat.options.temperature=0.7